baseURL = "https://nickdirienzo.com/"
author = "Nick DiRienzo"
# copyright = "Copyright © 2008–2019, Steve Francia and the lee.so; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[module]
[[module.imports]]
    path = 'github.com/nanxiaobei/hugo-paper'

# ------------------------------
theme = "hugo-paper"
title = "Nick DiRienzo"

[params]
  color = 'linen'

  twitter = 'nickdirienzo'
  github = 'nickdirienzo'
  linkedin = 'nickdirienzo'

  avatar = 'https://media.licdn.com/dms/image/D5603AQESPPrqfVDE8g/profile-displayphoto-shrink_800_800/0/1684262904947?e=1700092800&v=beta&t=XG-LLpLwynLkRWcZIe9v8KG-AdfGz078Kobqhcj29RQ'
  name = 'Nick DiRienzo'
  bio = ''
  monoDarkIcon = true
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
